### ISSUE TITLE
MIRFlickr数据集是否复现论文里结果

### ISSUE THREAD

**Issue by gujingzi** [idejie/DJSRH3#1]
MIRFlickr数据集是否复现论文里结果

**Comment by idejie** [comment]
可以

**Comment by gujingzi** [comment]
我直接跑了您的代码  MIRFlickr 的准确率i-t和t-i一样 0.612而且迭代多少次都不变   我求的是top50的结果，请问可能是什么问题

**Comment by idejie** [comment]
我这跑得结果没有问题，您可以把结果share一下吗?我看一下问题在哪

**Comment by idejie** [comment]
刚刚重新跑的结果，应该是略高于作者report的值的
